spring.application.name=invernadero
spring.datasource.url=jdbc:postgresql://localhost:5432/invernaderoeis
spring.datasource.username=postgres
spring.datasource.password=Joseph.0603

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.devtools.restart.poll-interval=1000
spring.devtools.restart.quiet-period=500

jwt.secret=mi_clave_secreta_para_invernadero_2026
jwt.expiration=86400000

spring.messages.basename=i18n/messages
spring.messages.encoding=UTF-8

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=josephguma0603@gmail.com
spring.mail.password=omzv aorz uodn qxgr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.security.oauth2.client.registration.google.client-id=659127983136-vhe91udn9v8i2qmbmdmagl4vf446dgdn.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email